# Generated by Django 4.2.9 on 2024-05-19 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_poste'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Poste',
        ),
    ]
