# Generated by Django 4.2.9 on 2024-05-21 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_certification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certification',
        ),
    ]
