# Generated by Django 4.2.9 on 2024-05-21 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='employe',
        ),
    ]
