# Generated by Django 4.2.9 on 2024-05-21 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0011_remove_certification_employe'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='employe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
