# Generated by Django 4.2.9 on 2024-05-21 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_certification_employe_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='employe',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
