# Generated by Django 4.2.9 on 2024-05-22 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
