# Generated by Django 4.2.9 on 2024-05-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_employee_poste'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipeProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_debut', models.DateField()),
                ('employes', models.ManyToManyField(related_name='equipes_projet', to='home.employee')),
            ],
        ),
    ]
